controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - gripper_finger_1_joint_1
      - gripper_finger_2_joint_1
      - gripper_finger_middle_joint_1
initial:  # Define initial robot poses per group
  - group: arm
    pose: up
  - group: gripper
    pose: open_grip